#pragma once

static const char* imageShader = \
"#version 430\n"
"varying vec2 fragCoord;\n"
"uniform sampler2D gm_BaseTexture;\n"
"#define px (vec2(7.0)/vec2(1280.,720.))\n"
"vec4 GetBloom(vec2 uv)"
"{"
"float numSamples=1.;"
"vec4 color=vec4(0);"
"for(float x=-5.;x<=5.;x+=1.)"
"for(float y=-5.;y<=5.;y+=1.)"
"{"
"vec4 addColor=texture2D(gm_BaseTexture,uv+vec2(x,y)*px);"
"if(max(addColor.x,max(addColor.y,addColor.z))>.8)"
"{"
"float dist=length(vec2(x,y))+1.;"
"vec4 glowColor=max(addColor*128./pow(dist,2.),vec4(0));"
"if(max(glowColor.x,max(glowColor.y,glowColor.z))>.9)"
"color+=glowColor,numSamples+=1.;"
"}"
"}"
"return color/numSamples;"
"}"
"void main()"
"{"
"vec2 iResolution = vec2(1280.,720.);"
"vec2 uv=fragCoord.xy/iResolution.xy;"
"vec4 box=texture2D(gm_BaseTexture,uv);"
"gl_FragColor=box+.05*GetBloom(uv);"
"}";